config/routes.rb
Rails.application.routes.draw do
  require "admin_constraint"
  mount Ckeditor::Engine => "/ckeditor", constraints: AdminConstraint.new

  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end
  
  devise_for :users

  devise_scope :user do 
    get "/admin" => "devise/sessions#new" 
  end
  
  root 'home#index'

  match '/about'                                      => 'home#about',                               via: [:get],            :as      => 'about'
  match '/connect'                                    => 'home#connect',                             via: [:get],            :as      => 'connect'
  match '/privacy-policy'                             => 'home#privacy_policy',                      via: [:get],            :as      => 'privacy_policy'
  
  get '/contact', to: redirect('/connect')
  get '/contact-us', to: redirect('/connect')
  get '/lets-meet', to: redirect('/connect')
  get '/our-work', to: redirect('/portfolio')
  get '/insights', to: redirect('/blogs')
  get '/about-us', to: redirect('/about')
  get '/services', to: redirect('/about')

  match '/portfolio'                                  => 'portfolio#index',                          via: [:get],            :as      => 'portfolio'
  match '/portfolio/boca-luxury-realty'               => 'portfolio#boca_luxury_realty',             via: [:get],            :as      => 'boca_luxury_realty'
  match '/portfolio/gcg-group-rebrand'                => 'portfolio#gcg_group_rebrand',              via: [:get],            :as      => 'gcg_group_rebrand'
  match '/portfolio/old-palm-golf-club'                    => 'portfolio#oldpalm',                  via: [:get],            :as      => 'oldpalm'
  match '/portfolio/fau'                              => 'portfolio#fau',                            via: [:get],            :as      => 'fau'
  match '/portfolio/graham-legal'                     => 'portfolio#graham_legal',                   via: [:get],            :as      => 'graham_legal'
  match '/portfolio/stein-posner'                     => 'portfolio#stein_posner',                   via: [:get],            :as      => 'stein_posner'

  match "/contacts"              =>        "contacts#create",              via: [:post]

  get '/sitemap.xml', to: redirect("https://s3.amazonaws.com/keenwebsite/sitemaps/sitemap.xml.gz", status: 301)

  #########################################
  #==news url for blog model
  #########################################
    get "/blogs", to: "blogs#index", as: :blogs
    post "blogs", to: "blogs#create"
    get "/blogs/new", to: "blogs#new", as: :new_blog
    get "/blogs/:category", to: "blogs#index_category", as: :blogs_index_category
    get "/:title_for_slug/edit", to: "blogs#edit", as: "edit_blog"
    get "/:title_for_slug", to: "blogs#show", as: "blog"
    patch "/:title_for_slug", to: "blogs#update"
    put "/:title_for_slug", to: "blogs#update"
    delete "/:title_for_slug", to: "blogs#destroy"


  match "*path", to: "home#catch_all", via: :all
  
end 
 

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :category

  validates :title, uniqueness: {case_sensitive: false}

  before_create :title_url_it
  before_save :remove_img
  # after_commit :set_imgs, on: [:create, :update]

  has_many :images, as: :imageable, :class_name => "Blog::Asset", dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  
  #This is for SEO purposes, you want the url to be the title of the blog instead of its ID
  def title_url_it
    self.title_for_slug = title.downcase.squish.parameterize("-")
  end

  def remove_img
    nokogiri_html_document =  Nokogiri::HTML(self.content) #heroku does not like tmp directory
    nokogiri_html_document.search('img').each do |img|
      img.remove
    end
    nokogiri_html_document.search('a').each { |node| node.replace(node.text) }
    self.content_index = nokogiri_html_document
    #note that if you call self.save here, you might run into infinite loops (stack level too deep), even for after_save, after_create and after_update callbacks
  end

  # def set_imgs
  #   self.update_attributes(image_medium: self.images[0].pic.url(:medium)) if self.images.present?
  #   self.update_attributes(image_large: self.images[0].pic.url(:large)) if self.images.present?
  #   self.image_medium = self.images[0].pic.url(:medium) if self.images.present?
  #   self.image_large = self.images[0].pic.url(:large) if self.images.present?
  # end

end

app/models/blog/asset.rb
class Blog::Asset < Image
  
  ##============================================================##
  ## Paperclip Interpolates
  ##============================================================##
  Paperclip.interpolates :imageable_type do |attachment, style|
    attachment.instance.imageable_type.downcase
  end

  Paperclip.interpolates :imageable_id do |attachment, style|
    attachment.instance.imageable_id
  end

  has_attached_file :pic,
    :path => "#{Rails.env}/:imageable_type/:imageable_id/:style/:filename",
    :styles => { 
      :medium => ["420x250>", :jpg], 
      :large => ["950x600>", :jpg]
    },
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    }
    # :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }

  validates_attachment :pic, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }, presence: true

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @blogs = Blog.order(pubdate: :desc).page(params[:page]).per_page(6)
    @categories = Category.order(name: :asc)
  end

  def index_category
    @blogs = Blog.where(category_id: Category.find_by(category_slug: params[:category]).id).order(pubdate: :desc).page(params[:page]).per_page(6)
    @categories = Category.order(name: :asc)
    render :index
  end

  def show
    # this is because our blog urls start from root path and when someone tries to route to 
    # /esh it was trying to find a blog with title esh and giving error because set blog function was returning nil.
    if !@blog.present?
      render 'home/catch_all'
      # return redirect_to :controller => 'home', :action => 'catch_all'
    else
      @related_blogs = Blog.where(category_id: @blog.category_id).where.not(id: @blog.id).last(3)
      @categories = Category.order(name: :asc)
    end
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      set_imgs
      redirect_to blog_path(@blog.title_for_slug), notice: 'Blog was successfully created.'
    else
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      set_imgs
      redirect_to blog_path(@blog.title_for_slug), notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: 'Blog was successfully destroyed.'
  end

  private

    def set_blog
      @blog = Blog.find_by(title_for_slug: params[:title_for_slug])
    end

    def set_imgs
      @blog.image_medium = @blog.images.order(updated_at: :desc).first.pic.url(:medium) if @blog.images.present?
      @blog.image_large = @blog.images.order(updated_at: :desc).first.pic.url(:large) if @blog.images.present?
      @blog.save
    end

    def blog_params
      params.require(:blog).permit(:title, :content, :content_index, :title_for_slug, :pubdate, :category_id, :meta_description, :meta_keywords, images_attributes: [:id, :pic, :name, :_destroy])
    end

end

app/views/blogs/_categories.html.erb
<div class="col-lg-3 col-md-12 col-sm-12 col-xs-12 pull-right left-border">
  <h3 class="mb20">Categories</h3>
  <ul class="cats">
    <li><a href="/blogs" style="color: #333333;">All</a></li>
    <% @categories.each do |category| %>
      <li class="<%= is_category_active?(category.category_slug)%>"><a href="/blogs/<%= category.category_slug %>" style="color: #333333;"><%= category.name %></a></li>
    <% end %>  
  </ul>
  <div class="clearfix"></div>
  <h3 class="mt30 newsletter noshow1199andunder">Subscribe to Our Newsletter</h3>
  <form action="https://keenability.createsend.com/t/d/s/akrkik/" method="post" id="subForm" class="noshow1199andunder">
      <input type="text" id="fieldEmail" name="cm-akrkik-akrkik" class="form-control blak-form" placeholder="Email Address" required="">
      <input type="submit" class="submit blak-btn" value="+">
  </form>
  <div class="lets_meet">
    <a data-toggle="modal" data-target="#myModal" class="go_to_connect"><img src="https://s3.amazonaws.com/keenwebsite/general/lets_meet_01.png" onmouseover="this.src='https://s3.amazonaws.com/keenwebsite/general/lets_meet_02.png'" onmouseout="this.src='https://s3.amazonaws.com/keenwebsite/general/lets_meet_01.png'" alt="">
    </a>
  </div>
</div>

app/views/blogs/_form.html.erb
<%= form_for(blog, :url => (blog.new_record? ? blogs_url : blog_path(blog.title_for_slug)), :html => { :multipart => true }) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.cktext_area :content, class: "form-control ckeditor", required: true %>
  </div>

  <div class="form-group">
    <%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: "Select Category"}, {class: "form-control", required: true} %>
  </div>

  <div class="form-group">
    <%= f.label :meta_description %>
    <%= f.text_field :meta_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :meta_keywords %>
    <%= f.text_field :meta_keywords, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.fields_for :images, @blog.images.build do |t| %>
      <%= t.label :pic, "Main Image" %> <br>

      <% if @blog.images.exists? %>
        <%= image_tag @blog.image_medium, id: 'current_image', class: 'mb15' %><br/>
      <% else %>
        <img id="current_image" class="mb5" src="#" alt="">
      <% end %>

      <%= t.file_field :pic, style: "padding: 4px;" %>  
      <%#= In order to make multiple file uploads you'd have to do it like you did in oldpalm, add multiple true, and loop through params[:pic] in your controller and create images that way %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :pubdate %><br>
    <% if !@blog.pubdate.present? %>
      <%= f.date_field :pubdate, value: Date.today, class:'form-control', required: true %>
    <% else %>
      <%= f.date_field :pubdate, class:'form-control', required: true %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: "form-control btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<% provide(:title, 'GCG Ground News') %>
<% content_for :head do%>
  <!-- <meta name="description" content="home description"> -->
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">

      <h1>Editing Blog</h1>

      <%= render 'form', blog: @blog %>

      <div class="mt15 mb30">
        <%= link_to '< Back', blogs_path, class: 'btn btn-warning' %>
        <%= link_to 'Show Blog', blog_path(@blog.title_for_slug), class: 'btn btn-warning' %> 
      </div>

    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<% provide(:title, 'Keen Insights | Keenability Boca Raton') %>
<% content_for :head do%>
  <meta name="description" content="Looking for some free marketing tips and strategies? Browse our marketing insights blog for the latest news and pontification.">
  <link rel="canonical" href="<%= request.url %>"/>

  <meta name="author" content="Keenability">
  <meta property="article:author" content="https://www.facebook.com/Keenability">

  <!-- Twitter Card data --> 
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@Keenability">
  <meta name="twitter:title" content="Keen Insights | Keenability Boca Raton">
  <meta name="twitter:description" content="Looking for some free marketing tips and strategies? Browse our marketing insights blog for the latest news and pontification.">
  <meta name="twitter:creator" content="@Keenability"> 
  <%# Twitter summary card with large image must be at least 280x150px  %>
  <meta name="twitter:image" content="https://s3.amazonaws.com/keenwebsite/blogs/Main_blog_Insights_header.jpg">
  <meta name="twitter:image:src" content="https://s3.amazonaws.com/keenwebsite/blogs/Main_blog_Insights_header.jpg">
  <meta name="twitter:domain" content="http://www.keenability.com">


  <!-- Open Graph data --> 
  <meta property="og:locale" content="en" /> 
  <meta property="og:title" content="Keen Insights | Keenability Boca Raton" /> 
  <meta property="og:type" content="article" /> 
  <meta property="og:url" content="<%= request.url %>" /> 
  <meta property="og:image" content="https://s3.amazonaws.com/keenwebsite/blogs/Main_blog_Insights_header.jpg" /> 
  <meta property="og:description" content="Looking for some free marketing tips and strategies? Browse our marketing insights blog for the latest news and pontification." /> 
  <meta property="og:site_name" content="Keenability" /> 
  <meta property="fb:admins" content="199462610236146" />
  <%# https://www.facebook.com/profile.php?id=199462610236146 %>

  <!-- GOOGLE Structured data -->
  <script type="application/ld+json">
  {
   "@context": "https://schema.org",
   "@type": "Website",
   "publisher": {
     "@type": "Organization",
     "name": "Keenability",
     "logo": {
       "@type": "ImageObject",
       "url": "https://s3.amazonaws.com/keenwebsite/general/home_keen_logo.png",
       "width": 1159,
       "height": 260
     }
   },
   "url": "<%= request.url %>",
   "image": {
     "@type": "ImageObject",
     "url": "https://s3.amazonaws.com/keenwebsite/blogs/Main_blog_Insights_header.jpg"
   },
   "mainEntityOfPage": {
     "@type": "WebPage",
     "@id": "<%= request.url %>"
   },
   "description": "Looking for some free marketing tips and strategies? Browse our marketing insights blog for the latest news and pontification."
  }
  </script>
  <!-- end local meta tags -->
<% end %>

<%= render 'layouts/static_header' %>

<div class="heroline"></div>
<div class="hero-blogs"></div>
<div class="heroline"></div>

<div class="container mt40 mb50">

  <% if current_user.try(:admin?) %>
  <div class="row mb60">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <%= link_to 'New Blog', new_blog_path, class:"btn btn-warning" %>
    </div>
  </div>
  <% end %>

  <div class="row">
    <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
      <% @blogs.each_with_index do |blog, i| %>
        <% if i.even? %>
          <div class="row mb40">
            
            <div class="col-sm-6 col-xs-12">
              <%= link_to blog_path(blog.title_for_slug) do %> 
                <%= image_tag(blog.image_medium, class:'img-responsive reversealignment') if blog.image_medium.present? %>
              <% end %>
            </div>
            <div class="col-sm-6 col-xs-12 text-left">
              <h4><%= link_to blog.title, blog_path(blog.title_for_slug), class: 'h2 index_blogs_title' %></h4>
              <p><%= link_to HTML_Truncator.truncate(blog.content_index, 25).html_safe, blog_path(blog.title_for_slug), class: "index_blogs_snippet" %></p>
              <div class="pull-left">
                <%#= link_to 'Read More', blog_path(blog.title_for_slug), class:"btn btn-gray" %>
                <%= link_to 'Edit', edit_blog_path(blog.title_for_slug), class:"btn btn-gray" if current_user.try(:admin?)%>
                <%= link_to 'Destroy', blog_path(blog.title_for_slug), class:"btn btn-gray", method: :delete, data: { confirm: 'Are you sure?' } if current_user.try(:admin?) %>
              </div>
            </div>
          </div>
        <% else %>
          <div class="row mb40">
            <div class="col-sm-6 col-xs-12 mobileonly">
              <%= link_to blog_path(blog.title_for_slug) do %> 
                <%= image_tag(blog.image_medium, class:'img-responsive') if blog.image_medium.present? %>
              <% end %>
            </div>
            <div class="col-sm-6 col-xs-12 myalignment">
              <h4><%= link_to blog.title, blog_path(blog.title_for_slug), class: 'h2 index_blogs_title' %></h4>
              <p><%= link_to HTML_Truncator.truncate(blog.content_index, 25).html_safe, blog_path(blog.title_for_slug), class: "index_blogs_snippet" %></p>
              <div class="myalignment">
                <%#= link_to 'Read More', blog_path(blog.title_for_slug), class:"btn btn-gray" %>
                <%= link_to 'Edit', edit_blog_path(blog.title_for_slug), class:"btn btn-gray" if current_user.try(:admin?)%>
                <%= link_to 'Destroy', blog_path(blog.title_for_slug), class:"btn btn-gray", method: :delete, data: { confirm: 'Are you sure?' } if current_user.try(:admin?) %>
              </div>
            </div>
            <div class="col-sm-6 col-xs-12 hidden-xs">
              <%= link_to blog_path(blog.title_for_slug) do %> 
                <%= image_tag(blog.image_medium, class:'img-responsive') if blog.image_medium.present? %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>

      <div id="myId" class="text-center col-md-12" data-last-page="<%= @blogs.total_pages %>">
        <%= will_paginate @blogs %>
      </div>
      
    </div>
    <%= render partial: 'categories' %>
  </div>

</div>
  
<%= render 'layouts/footer' %>  

app/views/blogs/new.html.erb
<% provide(:title, 'GCG Ground News') %>
<% content_for :head do%>
  <!-- <meta name="description" content="home description"> -->
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <h1>New Blog</h1>

      <%= render 'form', blog: @blog %>

      <div class="mt30 mb30">
         <%= link_to 'Back', blogs_path, class: 'btn btn-warning' %>
      </div>
     
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<% provide(:title, "Keen Insights | Keenability Boca Raton | #{@blog.title}") %>
<% content_for :head do%>
  <meta name="description" content="<%= @blog.meta_description %>">
  <meta name="keywords" content="<%= @blog.meta_keywords %>">
  <link rel="canonical" href="<%= request.url %>"/>

  <meta name="author" content="Keenability">
  <meta property="article:author" content="https://www.facebook.com/Keenability">

  <!-- Twitter Card data --> 
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@Keenability">
  <meta name="twitter:title" content="<%= @blog.title %>">
  <meta name="twitter:description" content="<%= @blog.meta_description %>">
  <meta name="twitter:creator" content="@Keenability"> 
  <%# Twitter summary card with large image must be at least 280x150px  %>
  <meta name="twitter:image" content="<%= @blog.image_large %>">
  <meta name="twitter:image:src" content="<%= @blog.image_large %>">
  <meta name="twitter:domain" content="http://www.keenability.com">


  <!-- Open Graph data --> 
  <meta property="og:locale" content="en" /> 
  <meta property="og:title" content="<%= @blog.title %>" /> 
  <meta property="og:type" content="article" /> 
  <meta property="og:url" content="<%= request.url %>" /> 
  <meta property="og:image" content="<%= @blog.image_large %>" /> 
  <meta property="og:description" content="<%= @blog.meta_description %>" /> 
  <meta property="og:site_name" content="Keenability" /> 
  <meta property="article:published_time" content="<%= @blog.pubdate %>" /> 
  <meta property="article:modified_time" content="<%= @blog.pubdate > @blog.updated_at ? @blog.pubdate : @blog.updated_at %>" /> 
  <meta property="article:tag" content="<%= @blog.meta_keywords %>" />
  <meta property="fb:admins" content="199462610236146" />
  <%# https://www.facebook.com/profile.php?id=199462610236146 %>

  <!-- GOOGLE Structured data -->
  <script type="application/ld+json">
  {
   "@context": "https://schema.org",
   "@type": "Website",
   "publisher": {
     "@type": "Organization",
     "name": "Keenability",
     "logo": {
       "@type": "ImageObject",
       "url": "https://s3.amazonaws.com/keenwebsite/general/home_keen_logo.png",
       "width": 1159,
       "height": 260
     }
   },
   "url": "<%= request.url %>",
   "image": {
     "@type": "ImageObject",
     "url": "<%= @blog.image_large %>"
   },
   "mainEntityOfPage": {
     "@type": "WebPage",
     "@id": "<%= request.url %>"
   },
   "description": "<%= @blog.meta_description %>"
  }
  </script>
  <!-- end local meta tags -->
<% end %>

<%= render 'layouts/static_header' %>

<div class="heroline"></div>
<div class="hero-blogs"></div>
<div class="heroline"></div>

<div class="container mt40 mb50">

  <div class="row">
    <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
      <h4><%= @blog.title %></h4>
      <p class="small"><%= @blog.pubdate.strftime("%B %d, %Y") if @blog.pubdate.present? %></p>
      <p class="mb30 share_social">
        <img src="https://s3.amazonaws.com/keenwebsite/blogs/share_button.jpg" alt="" width="55">
        <a href='<%= "https://www.facebook.com/sharer/sharer.php?u=#{request.url}" %>' class="ml25" target="blank"><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
        <a href='<%= "http://www.twitter.com/intent/tweet?text=#{@blog.meta_description}&url=#{request.url}" %>' class="ml7" target="blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
        <a href='<%= "https://www.linkedin.com/cws/share?url=#{request.url}" %>' class="ml7" target="blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
      </p>

      <%= image_tag(@blog.image_large, class:'img-responsive') if @blog.image_large.present? %>
      <p class="mt30"><%= simple_format(@blog.content).html_safe %></p>
      <div class="mt40">
        <%= link_to 'Back', blogs_path, class: "btn btn-gray mb30" if current_user.try(:admin?) %>
        <%= link_to 'Edit', edit_blog_path(@blog.title_for_slug), class: "btn btn-gray mb30" if current_user.try(:admin?) %>
      </div>
    </div>

    <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12 pull-right left-border">
      <h3 class="mb20">Categories</h3>
      <ul class="cats">
        <li><a href="/blogs" style="color: #333333;">All</a></li>
        <% @categories.each do |category| %>
          <li class="<%= 'cat_active' if @blog.category.category_slug == category.category_slug %>"><a href="/blogs/<%= category.category_slug %>" style="color: #333333;"><%= category.name %></a></li>
        <% end %>  
      </ul>
      <div class="clearfix"></div>
      <h3 class="mt30 newsletter noshow1199andunder">Subscribe to Our Newsletter</h3>
      <form action="https://keenability.createsend.com/t/d/s/akrkik/" method="post" id="subForm" class="noshow1199andunder">
          <input type="text" id="fieldEmail" name="cm-akrkik-akrkik" class="form-control blak-form" placeholder="Email Address" required="">
          <input type="submit" class="submit blak-btn" value="+">
      </form>
      <div class="lets_meet">
        <a data-toggle="modal" data-target="#myModal" class="go_to_connect"><img src="https://s3.amazonaws.com/keenwebsite/general/lets_meet_01.png" onmouseover="this.src='https://s3.amazonaws.com/keenwebsite/general/lets_meet_02.png'" onmouseout="this.src='https://s3.amazonaws.com/keenwebsite/general/lets_meet_01.png'" alt="">
        </a>
      </div>
      <h3 class="mt80 mb30 rposts noshow1199andunder">RELATED POSTS:</h3>
      <% @related_blogs.each do |rblog| %>
        <div class="rblogs mb30 noshow1199andunder">
          <%= link_to blog_path(rblog.title_for_slug) do %> 
            <%= image_tag(rblog.image_medium, class:'img-responsive') if rblog.image_medium.present? %>
          <% end %>
          <h4><%= link_to rblog.title, blog_path(rblog.title_for_slug), class: 'h2 index_blogs_title' %></h4>
          <p><%= link_to HTML_Truncator.truncate(rblog.content_index, 20).html_safe, blog_path(rblog.title_for_slug), class: "index_blogs_snippet" %></p>
          <%#= link_to 'Read More', blog_path(rblog.title_for_slug), class:"btn btn-gray" %>
        </div>
      <% end %>

    </div>

  </div>
</div>

<%= render 'layouts/footer' %>