config/routes.rb
Rails.application.routes.draw do
  require "admin_constraint"
  mount Ckeditor::Engine => "/ckeditor", constraints: AdminConstraint.new

  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end
  
  devise_for :users

  devise_scope :user do 
    get "/admin" => "devise/sessions#new" 
  end
  
  root 'home#index'

  match '/about'                                      => 'home#about',                               via: [:get],            :as      => 'about'
  match '/connect'                                    => 'home#connect',                             via: [:get],            :as      => 'connect'
  match '/privacy-policy'                             => 'home#privacy_policy',                      via: [:get],            :as      => 'privacy_policy'
  
  get '/contact', to: redirect('/connect')
  get '/contact-us', to: redirect('/connect')
  get '/lets-meet', to: redirect('/connect')
  get '/our-work', to: redirect('/portfolio')
  get '/insights', to: redirect('/blogs')
  get '/about-us', to: redirect('/about')
  get '/services', to: redirect('/about')

  match '/portfolio'                                  => 'portfolio#index',                          via: [:get],            :as      => 'portfolio'
  match '/portfolio/boca-luxury-realty'               => 'portfolio#boca_luxury_realty',             via: [:get],            :as      => 'boca_luxury_realty'
  match '/portfolio/gcg-group-rebrand'                => 'portfolio#gcg_group_rebrand',              via: [:get],            :as      => 'gcg_group_rebrand'
  match '/portfolio/old-palm-golf-club'                    => 'portfolio#oldpalm',                  via: [:get],            :as      => 'oldpalm'
  match '/portfolio/fau'                              => 'portfolio#fau',                            via: [:get],            :as      => 'fau'
  match '/portfolio/graham-legal'                     => 'portfolio#graham_legal',                   via: [:get],            :as      => 'graham_legal'
  match '/portfolio/stein-posner'                     => 'portfolio#stein_posner',                   via: [:get],            :as      => 'stein_posner'

  match "/contacts"              =>        "contacts#create",              via: [:post]

  get '/sitemap.xml', to: redirect("https://s3.amazonaws.com/keenwebsite/sitemaps/sitemap.xml.gz", status: 301)

  #########################################
  #==news url for blog model
  #########################################
    get "/blogs", to: "blogs#index", as: :blogs
    post "blogs", to: "blogs#create"
    get "/blogs/new", to: "blogs#new", as: :new_blog
    get "/blogs/:category", to: "blogs#index_category", as: :blogs_index_category
    get "/:title_for_slug/edit", to: "blogs#edit", as: "edit_blog"
    get "/:title_for_slug", to: "blogs#show", as: "blog"
    patch "/:title_for_slug", to: "blogs#update"
    put "/:title_for_slug", to: "blogs#update"
    delete "/:title_for_slug", to: "blogs#destroy"


  match "*path", to: "home#catch_all", via: :all
  
end 
 

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def connect
    @thank_you = session[:thank_you]
    session[:thank_you] = nil
  end

  def catch_all
  end
end

app/views/home/about.html.erb
<% provide(:title, 'The Who, What, Where, Why, and How | Keenability Boca Raton') %>
<% content_for :head do%>
  <meta name="description" content="Since our 2014 founding, we've only had one directive: exceed expectations. Our team is led by South Florida natives with decades of marketing experience.">
  <link rel="canonical" href="<%= request.url %>"/>
  <meta name="turbolinks-cache-control" content="no-cache">


  <meta name="author" content="Keenability">
  <meta property="article:author" content="https://www.facebook.com/Keenability">

  <!-- Twitter Card data --> 
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@Keenability">
  <meta name="twitter:title" content="The Who, What, Where, Why, and How | Keenability Boca Raton">
  <meta name="twitter:description" content="Since our 2014 founding, we've only had one directive: exceed expectations. Our team is led by South Florida natives with decades of marketing experience.">
  <meta name="twitter:creator" content="@Keenability"> 
  <%# Twitter summary card with large image must be at least 280x150px  %>
  <meta name="twitter:image" content="https://s3.amazonaws.com/keenwebsite/about/about_sample_work_pic.jpg">
  <meta name="twitter:image:src" content="https://s3.amazonaws.com/keenwebsite/about/about_sample_work_pic.jpg">
  <meta name="twitter:domain" content="http://www.keenability.com">


  <!-- Open Graph data --> 
  <meta property="og:locale" content="en" /> 
  <meta property="og:title" content="The Who, What, Where, Why, and How | Keenability Boca Raton" /> 
  <meta property="og:type" content="article" /> 
  <meta property="og:url" content="<%= request.url %>" /> 
  <meta property="og:image" content="https://s3.amazonaws.com/keenwebsite/about/about_sample_work_pic.jpg" /> 
  <meta property="og:description" content="Since our 2014 founding, we've only had one directive: exceed expectations. Our team is led by South Florida natives with decades of marketing experience." /> 
  <meta property="og:site_name" content="Keenability" /> 
  <meta property="fb:admins" content="199462610236146" />
  <%# https://www.facebook.com/profile.php?id=199462610236146 %>

  <!-- GOOGLE Structured data -->
  <script type="application/ld+json">
  {
   "@context": "https://schema.org",
   "@type": "Website",
   "publisher": {
     "@type": "Organization",
     "name": "Keenability",
     "logo": {
       "@type": "ImageObject",
       "url": "https://s3.amazonaws.com/keenwebsite/general/home_keen_logo.png",
       "width": 1159,
       "height": 260
     }
   },
   "url": "<%= request.url %>",
   "image": {
     "@type": "ImageObject",
     "url": "https://s3.amazonaws.com/keenwebsite/about/about_sample_work_pic.jpg"
   },
   "mainEntityOfPage": {
     "@type": "WebPage",
     "@id": "<%= request.url %>"
   },
   "description": "Since our 2014 founding, we've only had one directive: exceed expectations. Our team is led by South Florida natives with decades of marketing experience."
  }
  </script>
  <!-- end local meta tags -->
<% end %>



<%= render 'layouts/static_header' %>

<div class="hero-about"></div>

<div class="container mt40 mb30">
	

	<div class="row">
		<div class="col-md-4 text-right">
			<img src="https://s3.amazonaws.com/keenwebsite/about/about_icon.gif" class="gif"	alt="Keenability">
		</div>
		<div class="col-md-4">
			<p class="bold">
				If you're after the same old same old, then these aren't the droids you're looking for. Our Boca Raton advertising agency is setting new standards.
			</p>
		</div>
		<div class="col-md-4"></div>
	</div>
	
	<div class="row mt40">
		<div class="col-md-4 text-right">
			<h2>Capabilities</h2>
			<p>We approach marketing with the same tenacity as a certain young wizard trying to defeat He Who Must Not Be Named. After all, we're kind of wizards in our own right, at least when it comes to creating beautiful brands and unbeatable marketing strategies.</p>
		</div>
		<div class="col-md-8">
			<img src="https://s3.amazonaws.com/keenwebsite/about/about_sample_work_pic.jpg" width="100%" height="auto" alt="">				
		</div>
	</div>
	

	<div class="row mt40 noshow991andunder">
		<div class="col-md-6 text-right">
		  <div class="row">
		  	<div class="col-md-4"></div>
				<div class="col-md-4 text-right">
					<img src="https://s3.amazonaws.com/keenwebsite/about/creative_icon.jpg" alt="" class="img-responsive" id="creative_img">
				</div>
				<div class="col-md-4 text-left">
					<img src="https://s3.amazonaws.com/keenwebsite/about/digital_icon.jpg" alt="" class="img-responsive" id="digital_img">
				</div>
			</div>
		  <div class="row mt30">
			  <div class="col-md-4"></div>
				<div class="col-md-4 text-right">
					<img src="https://s3.amazonaws.com/keenwebsite/about/marketing_icon.jpg" alt="" class="img-responsive" id="marketing_img">
				</div>
				<div class="col-md-4 text-left">
					<img src="https://s3.amazonaws.com/keenwebsite/about/public_relations_icon.jpg" alt="" class="img-responsive" id="public_relations_img">
				</div>
			</div>
		</div>

		<div class="col-md-6" id="img_content">
		</div>
	</div>
	

	<div class="row mt20">
		<div class="col-md-offset-7 col-md-5 text-right">
			<h2>The #KeenTeam</h2>
			<p>We're too busy designing your new website and executing marketing strategy to pose for headshots. Instead, here's a look at our team in action.</p>
		</div>
	</div>
	

	<div class="row">
		<div class="col-lg-offset-6 col-lg-6 col-md-offset-5 col-md-7 col-sm-offset-4 col-sm-8 text-right">
      <a href="https://www.instagram.com/keenability/" target="blank">
        <img src="https://s3.amazonaws.com/keenwebsite/about/keen-instagram.jpg" width="450px" alt="" class="pb10 keen-instagram">
      </a>

			<div id="instafeed"></div>
		</div>
	</div>
	

	<div class="row mt40">
		<div class="col-md-4 text-right">
			<h2>Our partners<br><span style="font-weight: 200; color: #d3d3d3;">are talking</span></h2>
			<p>Keenability was founded on the belief that great results can only be achieved by functioning as an in-house marketing team, that just so happens to not be quite in-house. We don't have clients, we have partners, and we're ready for you to become one of them.</p>
		</div>
		<div class="col-md-8">
			<div class="owl-carousel owl-theme">
				<div class="item">
					<img src="https://s3.amazonaws.com/keenwebsite/about/about_testmonial_4.jpg" width="90%" height="auto" alt="">
				</div>
				<div class="item">
					<img src="https://s3.amazonaws.com/keenwebsite/about/about_testmonial_2.jpg" width="90%" height="auto" alt="">
				</div>
				<div class="item">
					<img src="https://s3.amazonaws.com/keenwebsite/about/about_testmonial_3.jpg" width="90%" height="auto" alt="">
				</div>
				<div class="item">
					<img src="https://s3.amazonaws.com/keenwebsite/about/about_testmonial.jpg" width="90%" height="auto" alt="">
				</div>
			</div>
		</div>
	</div>
	
	<div class="row mt50 mb50">
    <div class="col-xs-12 text-center lets_meet">
      <a data-toggle="modal" data-target="#myModal" class="go_to_connect"><img src="https://s3.amazonaws.com/keenwebsite/general/lets_meet_01.png" onmouseover="this.src='https://s3.amazonaws.com/keenwebsite/general/lets_meet_02.png'" onmouseout="this.src='https://s3.amazonaws.com/keenwebsite/general/lets_meet_01.png'" alt="">
      </a>
    </div>
	</div>


</div>

<%= render 'layouts/footer' %>

app/views/home/catch_all.html.erb
<%= render 'layouts/static_header' %>

<div class="heroline"></div>


<div class="container mt40 mb30 myerror">
  

  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 text center">
      <img src="https://s3.amazonaws.com/keenwebsite/general/sad_keen_404.jpg" class="center-block img-responsive" width="125" alt="Keenability">
      <h1 class="mt40 text-center pb20">Page Not Found</h1>
      <p class="mt20 text-center pb20" style="font-size: 15px;">
        Sorry, the page you requested cannot be found. <br>
        Perhaps you can find it in the list below.
      </p>
      <ul>
        <li class="text-center mt10 mb10"><a href="/about" class="error_page_link">About</a></li>
        <li class="text-center mt10 mb10"><a href="/portfolio" class="error_page_link">Portfolio</a></li>
        <li class="text-center mt10 mb10"><a href="/connect" class="error_page_link">Connect</a></li>
        <li class="text-center mt10 mb40"><a href="/blogs" class="error_page_link">Insights</a></li>
      </ul>
    </div>
  </div>
  

</div>


<%= render 'layouts/footer' %>

app/views/home/connect.html.erb
<% provide(:title, 'Call or E-mail Our Local Marketing Agency | Keenability Boca Raton') %>
<% content_for :head do%>
  <meta name="description" content="Contact our home base in Boca Raton by landline, e-mail, or even by owl! We make ourselves available to all past, current, and prospective clients.">
  <link rel="canonical" href="<%= request.url %>"/>

  <meta name="author" content="Keenability">
  <meta property="article:author" content="https://www.facebook.com/Keenability">

  <!-- Twitter Card data --> 
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@Keenability">
  <meta name="twitter:title" content="Call or E-mail Our Local Marketing Agency | Keenability Boca Raton">
  <meta name="twitter:description" content="Contact our home base in Boca Raton by landline, e-mail, or even by owl! We make ourselves available to all past, current, and prospective clients.">
  <meta name="twitter:creator" content="@Keenability"> 
  <%# Twitter summary card with large image must be at least 280x150px  %>
  <meta name="twitter:image" content="https://s3.amazonaws.com/keenwebsite/connect/connect_header.jpg">
  <meta name="twitter:image:src" content="https://s3.amazonaws.com/keenwebsite/connect/connect_header.jpg">
  <meta name="twitter:domain" content="http://www.keenability.com">


  <!-- Open Graph data --> 
  <meta property="og:locale" content="en" /> 
  <meta property="og:title" content="Call or E-mail Our Local Marketing Agency | Keenability Boca Raton" /> 
  <meta property="og:type" content="article" /> 
  <meta property="og:url" content="<%= request.url %>" /> 
  <meta property="og:image" content="https://s3.amazonaws.com/keenwebsite/connect/connect_header.jpg" /> 
  <meta property="og:description" content="Contact our home base in Boca Raton by landline, e-mail, or even by owl! We make ourselves available to all past, current, and prospective clients." /> 
  <meta property="og:site_name" content="Keenability" /> 
  <meta property="fb:admins" content="199462610236146" />
  <%# https://www.facebook.com/profile.php?id=199462610236146 %>

  <!-- GOOGLE Structured data -->
  <script type="application/ld+json">
  {
   "@context": "https://schema.org",
   "@type": "Website",
   "publisher": {
     "@type": "Organization",
     "name": "Keenability",
     "logo": {
       "@type": "ImageObject",
       "url": "https://s3.amazonaws.com/keenwebsite/general/home_keen_logo.png",
       "width": 1159,
       "height": 260
     }
   },
   "url": "<%= request.url %>",
   "image": {
     "@type": "ImageObject",
     "url": "https://s3.amazonaws.com/keenwebsite/connect/connect_header.jpg"
   },
   "mainEntityOfPage": {
     "@type": "WebPage",
     "@id": "<%= request.url %>"
   },
   "description": "Contact our home base in Boca Raton by landline, e-mail, or even by owl! We make ourselves available to all past, current, and prospective clients."
  }
  </script>
  <!-- end local meta tags -->
<% end %>

<%= render 'layouts/static_header' %>

<div class="hero-contact"></div>

<div class="container mt50 mb50">
	<div class="row">
		<div class="col-md-6 text-right">
			<h2 class="font-bold fts37">Ready to elevate<br> your brand?</h2>
		</div>
		<div class="col-md-6"></div>
	</div>
	<div class="row">
		<div class="col-md-6 text-right mt30">
			<p class="p_connect"><a href="mailto:hello@keenability.com" style="color: #45606a;">hello@keenability.com</a></p> 
			<p class="p_connect"><a href="tel:15617569720" style="color: #45606a;">561.756.9720</a></p>
			<br>
			<address>
				<p class="p_connect">4181 NW 1st Ave, Suite 8</p>
				<p class="p_connect">Boca Raton, Fl 33431</p>
			</address>
		</div>
		<div class="col-md-6 mt30">
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3574.1066402869887!2d-80.08662115300646!3d26.387742177795616!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88d91e729a78e127%3A0x661cc5a4ecfdfb6e!2sKeenability%2C+Inc.!5e0!3m2!1sen!2sus!4v1510006087929" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
		</div>
	</div>

	<div class="row">
    <div class="cform col-md-12 mt40" id="cform">
		  <%= form_for Contact.new, :url => contacts_url, method: :post do |f|  %>
		  <div class="row">
		    <div class="col-sm-6 phone">
		    	<h3 class="font-bold fts37"><%= @thank_you.present? ? @thank_you : "let's talk" %></h3>
		    </div>
		    <div class="col-sm-6">
		      <div class="form-group">
		        <%= f.label :name, class: "sr-only" %>
		        <%= f.text_field :name, class: "form-control text-right string", placeholder: "Full Name", required: true %>
		      </div>
		      <div class="form-group">
		        <%= f.label :email, class: "sr-only" %>
		        <%= f.email_field :email, class: "form-control text-right string", placeholder: "Email", required: true %>
		      </div>
		      <div class="form-group">
		        <%= f.label :phone_number, class: "sr-only" %>
		        <%= f.text_field :phone_number, class: "form-control text-right string", placeholder: "Phone", required: true %>
		      </div>
		      <div class="form-group">
		        <%= f.label :message, class: "sr-only" %>
		        <%= f.text_area :message, class: "form-control text-right pt50", rows: 1, placeholder: "Message", required: true %>
		      </div>
		      <div class="form-group">
		        <%= f.submit "Send", class: "btn btn-black pull-right" %>
		      </div>
		    </div>
		    <div class="col-sm-6 mt75 cpu">
          <% if @thank_you.present? %>
            <h3 class="font-bold fts37 color-peach"><%= @thank_you %></h3>
          <% else %>
  		    	<h3 class="font-bold fts37">let's talk</h3>
          <% end %>
		    </div>
		  </div>
		  <% end %>
		</div>
	</div>

</div>

<%= render 'layouts/footer' %>

app/views/home/index.html.erb
<% provide(:title, 'Amplify Your Story | Keenability Boca Raton') %>
<% content_for :head do%>
  <meta name="description" content="Keen creative and beautiful brands produced by our full-service Boca Raton marketing agency. Achieving your goals is the only way we measure success.">
  <meta name="keywords" content="">
  <link rel="canonical" href="<%= request.url %>"/>

  <meta name="author" content="Keenability">
  <meta property="article:author" content="https://www.facebook.com/Keenability">

  <!-- Twitter Card data --> 
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@Keenability">
  <meta name="twitter:title" content="Amplify Your Story | Keenability Boca Raton">
  <meta name="twitter:description" content="Keen creative and beautiful brands produced by our full-service Boca Raton marketing agency. Achieving your goals is the only way we measure success.">
  <meta name="twitter:creator" content="@Keenability"> 
  <%# Twitter summary card with large image must be at least 280x150px  %>
  <meta name="twitter:image" content="https://s3.amazonaws.com/keenwebsite/about/about_sample_work_pic.jpg">
  <meta name="twitter:image:src" content="https://s3.amazonaws.com/keenwebsite/about/about_sample_work_pic.jpg">
  <meta name="twitter:domain" content="http://www.keenability.com">


  <!-- Open Graph data --> 
  <meta property="og:locale" content="en" /> 
  <meta property="og:title" content="Amplify Your Story | Keenability Boca Raton" /> 
  <meta property="og:type" content="article" /> 
  <meta property="og:url" content="<%= request.url %>" /> 
  <meta property="og:image" content="https://s3.amazonaws.com/keenwebsite/about/about_sample_work_pic.jpg" /> 
  <meta property="og:description" content="Keen creative and beautiful brands produced by our full-service Boca Raton marketing agency. Achieving your goals is the only way we measure success." /> 
  <meta property="og:site_name" content="Keenability" /> 
  <meta property="fb:admins" content="199462610236146" />
  <%# https://www.facebook.com/profile.php?id=199462610236146 %>

  <!-- GOOGLE Structured data -->
  <script type="application/ld+json">
  {
   "@context": "https://schema.org",
   "@type": "Website",
   "publisher": {
     "@type": "Organization",
     "name": "Keenability",
     "logo": {
       "@type": "ImageObject",
       "url": "https://s3.amazonaws.com/keenwebsite/general/home_keen_logo.png",
       "width": 1159,
       "height": 260
     }
   },
   "url": "<%= request.url %>",
   "image": {
     "@type": "ImageObject",
     "url": "https://s3.amazonaws.com/keenwebsite/about/about_sample_work_pic.jpg"
   },
   "mainEntityOfPage": {
     "@type": "WebPage",
     "@id": "<%= request.url %>"
   },
   "description": "Keen creative and beautiful brands produced by our full-service Boca Raton marketing agency. Achieving your goals is the only way we measure success."
  }
  </script>
  <!-- end local meta tags -->
<% end %>

<div class="wrapper">
  
  <%= render 'layouts/header' %>
	
	<div class="page">
		
		<div class="relative">
			<div id="prlx_welcome_lyr_noparallax"></div>
			<div id="prlx_welcome_lyr_0"></div>
			<div id="prlx_welcome_lyr_1"></div>
			<div id="prlx_welcome_lyr_2"></div>
			<div id="prlx_welcome_lyr_3"></div>
		</div>
			
		<div class="relative">
			<a href="/about">
				<div id="prlx_about_lyr_noparallax"></div>
				<div id="prlx_about_lyr_0"></div>
				<div id="prlx_about_lyr_1"></div>
				<div id="prlx_about_lyr_2"></div>
				<div id="prlx_about_lyr_3"></div>
			</a>
		</div>

		<div class="relative">
			<a href="/portfolio">
				<div id="prlx_spot_lyr_noparallax"></div>
				<div id="prlx_spot_lyr_0"></div>
				<div id="prlx_spot_lyr_1"></div>
				<div id="prlx_spot_lyr_2"></div>
				<div id="prlx_spot_lyr_3"></div>
			</a>
		</div>

		<div class="relative">
			<a data-toggle="modal" data-target="#myModal" class="clickable go_to_connect">
				<div id="prlx_connect_lyr_noparallax"></div>
				<div id="prlx_connect_lyr_0"></div>
				<div id="prlx_connect_lyr_1"></div>
				<div id="prlx_connect_lyr_2"></div>
				<div id="prlx_connect_lyr_3"></div>
			</a>
		</div>

	</div>

	<%= render 'layouts/footer' %>

</div>

app/views/home/privacy_policy.html.erb
<% provide(:title, 'Amplify Your Story | Keenability Boca Raton - Privacy Policy') %>

<%= render 'layouts/static_header' %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>
        <img src="https://s3.amazonaws.com/keenwebsite/about/about_icon.gif" class="gif"  alt="Keenability">
        Privacy Policy
      </h1>
      <h3>Keenability.com Privacy Policy</h3>
        <p>
          This privacy policy has been compiled to better serve those who are concerned with how their ‘Personally identifiable information’ (PII) is being used online. PII, as used in US privacy law and information security, is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context. Please read our privacy policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance with our website.
        </p>

        <h3>What information do we collect?</h3>

        <p>
          When ordering or registering on our site, as appropriate, you may be asked to enter your Name, Email address, Phone number or other details to help you with your experience.
        </p>

        <h3>When do we collect information?</h3>

        <p>
          We collect information from you when you subscribe to a newsletter, fill out a form or enter information on our site.
        </p>

        <h3>How do we use your information?</h3>

        <p>
          We may use the information we collect from you when you register, make a purchase, sign up for our newsletter, respond to a survey or marketing communication, surf the website, or use certain other site features in the following ways:
        </p>

        <ul>
          <li>To improve our website in order to better serve you.</li>
          <li>To allow us to better service you in responding to your customer service requests.</li>
          <li>To send periodic emails regarding your order or other products and services.</li>
        </ul>

        <h3>How do we protect visitor information?</h3>

        <p>
          We do not use vulnerability scanning and/or scanning to PCI standards.
          We use an SSL certificate and implement security measures when a user:
        </p>

        <ul>
          <li>enters, submits, or accesses their information.</li>
        </ul>

        <p>We use a payment gateway provider.</p>

        <h3>Do we use ‘cookies’?</h3>

        <p>
          We use cookies to: <br>
          Compile aggregate data about site traffic and site interactions in order to offer better site experiences and tools in the future. We may also use trusted third party services that track this information on our behalf.
          It won’t affect the users experience
        </p>

        <h3>Third Party Disclosure</h3>

        <p>We do not sell, trade, or otherwise transfer Personally Identifiable Information.</p>

        <h3>Third party links</h3>

        <p>We do not include or offer third party products or services on our website.</p>

        <h3>Google</h3>

        <p>
          We use Google AdSense Advertising on our website. <br>
          Google, as a third party vendor, uses cookies to serve ads on our site. Google’s use of the DART cookie enables it to serve ads to our users based on their visit to our site and other sites on the Internet. Users may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy. <br>
          We have implemented the following:
        </p>
        <ul>
          <li>Remarketing with Google AdSense</li>
          <li>Google Display Network Impression Reporting</li>
          <li>Demographics and Interests Reporting</li>
        </ul>
        <p>
          We and third party vendors such as Google use:
          To compile data regarding user interactions with ad impressions, and other ad service functions as they relate to our website.
        </p>

        <p>Opting out:</p>
        
        <p>
          Users can set preferences for how Google advertises to you using the Google Ad Settings page. Alternatively, you can opt out by visiting the Network Advertising initiative opt out page or permanently using the Google Analytics Opt Out Browser add on.
        </p>

        <h3>California Online Privacy Protection Act</h3>

        <p>
          According to CalOPPA we agree to the following:
          Users can visit our site anonymously
          Once this privacy policy is created, we will add a link to it on our home page, or as a minimum on the first significant page after entering our website.
          Our Privacy Policy link includes the word ‘Privacy’, and can be easily be found on the page specified above.
        </p>
  
        <p>
          Users will be notified of any privacy policy changes: <br>
          • On our Privacy Policy Page <br>
          Users are able to change their personal information: <br>
          • By emailing us <br>
          • By calling us
        </p>

        <h3>How does our site handle do not track signals?</h3>

        <p>
          We honor them and do not track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place.
        </p>

        <h3>Does our site allow third party behavioral tracking?</h3>

        <p>
          We allow
        </p>

        <h3>COPPA (Children Online Privacy Protection Act)</h3>

        <p>We do not specifically market to children under 13</p>

        <h3>Fair Information Practices</h3>

        <p>
          In order to be in line with Fair Information Practices we will take the following responsive action, should a data breach occur: <br>
          We will notify the users via email
        </p>

        <ul>
          <li>Within 7 business days</li>
        </ul>
        
        <p>
          We agree to the individual redress principle, which requires that individuals have a right to pursue legally enforceable rights against data collectors and processors who fail to adhere to the law. This principle requires not only that individuals have enforceable rights against data users, but also that individuals have recourse to courts or a government agency to investigate and/or prosecute non-compliance by data processors
        </p>

        <h3>CAN SPAM Act</h3>
        
        <p>
          We collect your email address: <br>
          To send information, respond to inquiries, and/or other requests or questions. <br>
          To market to our mailing list or continue to send emails to your clients after the original transaction has occured <br>

          To be accordance with CANSPAM we agree to the following: <br>
          We will NOT use false, or misleading subjects or email addresses <br>
          We will identify the message as an advertisement in some reasonable way <br>
          We will include the physical address of our business or site headquarters <br>
          We will monitor third party email marketing services for compliance, if one is used. <br>
          We will honor opt-out/unsubscribe requests quickly <br>
          We will give an ‘opt-out’ or ‘unsubscribe’ option <br>

          If at any time you would like to unsubscribe from receiving future emails, you can
        </p>

        <ul>
          <li>Follow the instructions at the bottom of each email.</li>
        </ul>

        <h3>Contact Information</h3>

        <p>
          <a href="https://www.keenability.com" >keenability.com</a> <br>

          4181 NW 1st Ave, Suite 8 <br>
          Boca Raton, Florida 33431 <br>

          <a href="mailto:hello@keenability.com">hello@keenability.com</a> <br>
          <a href="tel:5617569720">561-756-9720</a><br>
        </p>      
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>